---
# handlers file for role_technitium

- name: restart technitium
  ansible.builtin.systemd:
    name: "{{ technitium_service_name }}"
    state: restarted
    daemon_reload: true
    enabled: true
